# Generated by Django 4.0.3 on 2022-05-08 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0002_peoplelist_admin_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peoplelist',
            old_name='admin_status',
            new_name='rol',
        ),
    ]
